// Mock data for demo mode (when database is not available)

export const mockProjects = [
  {
    id: '1',
    name: 'Acme Corp Cloud Migration',
    customerName: 'Acme Corporation',
    projectManager: 'John Smith',
    accountManager: 'Sarah Johnson',
    planType: 'PLATINUM',
    plannedStart: new Date('2026-01-15'),
    plannedEnd: new Date('2026-04-15'),
    actualStart: new Date('2026-01-15'),
    actualEnd: null,
    delayDays: 0,
    delayStatus: 'NOT_DELAYED',
    phase: 'MIGRATION',
    status: 'ACTIVE',
    sourcePlatform: 'On-Premise VMware',
    targetPlatform: 'AWS',
    estimatedCost: 150000,
    actualCost: null,
    description: 'Full infrastructure migration from on-premise VMware to AWS cloud.',
    notes: null,
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: '2',
    name: 'TechStart SaaS Migration',
    customerName: 'TechStart Inc',
    projectManager: 'Emily Davis',
    accountManager: 'Michael Brown',
    planType: 'GOLD',
    plannedStart: new Date('2026-02-01'),
    plannedEnd: new Date('2026-03-20'),
    actualStart: new Date('2026-02-01'),
    actualEnd: null,
    delayDays: 6,
    delayStatus: 'DELAYED',
    phase: 'VALIDATION',
    status: 'ACTIVE',
    sourcePlatform: 'Legacy CRM',
    targetPlatform: 'Salesforce',
    estimatedCost: 75000,
    actualCost: null,
    description: 'CRM migration from legacy system to Salesforce.',
    notes: null,
    createdAt: new Date('2026-01-25'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: '3',
    name: 'GlobalBank Data Center Move',
    customerName: 'Global Bank Ltd',
    projectManager: 'Robert Wilson',
    accountManager: 'Jennifer Lee',
    planType: 'PLATINUM',
    plannedStart: new Date('2025-11-01'),
    plannedEnd: new Date('2026-02-28'),
    actualStart: new Date('2025-11-01'),
    actualEnd: new Date('2026-03-15'),
    delayDays: 15,
    delayStatus: 'DELAYED',
    phase: 'COMPLETED',
    status: 'COMPLETED',
    sourcePlatform: 'Private Data Center',
    targetPlatform: 'Azure',
    estimatedCost: 500000,
    actualCost: 520000,
    description: 'Complete data center migration to Azure cloud.',
    notes: 'Project completed with minor delays due to compliance requirements.',
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2026-03-15'),
  },
  {
    id: '4',
    name: 'RetailMax E-commerce Platform',
    customerName: 'RetailMax',
    projectManager: 'Amanda Chen',
    accountManager: 'David Martinez',
    planType: 'SILVER',
    plannedStart: new Date('2026-03-01'),
    plannedEnd: new Date('2026-05-30'),
    actualStart: new Date('2026-03-01'),
    actualEnd: null,
    delayDays: 0,
    delayStatus: 'NOT_DELAYED',
    phase: 'KICKOFF',
    status: 'ACTIVE',
    sourcePlatform: 'Magento 1',
    targetPlatform: 'Shopify Plus',
    estimatedCost: 45000,
    actualCost: null,
    description: 'E-commerce platform migration from Magento to Shopify.',
    notes: null,
    createdAt: new Date('2026-02-20'),
    updatedAt: new Date('2026-03-25'),
  },
  {
    id: '5',
    name: 'HealthCare Plus EHR Migration',
    customerName: 'HealthCare Plus',
    projectManager: 'Dr. Lisa Thompson',
    accountManager: 'Chris Anderson',
    planType: 'GOLD',
    plannedStart: new Date('2026-01-10'),
    plannedEnd: new Date('2026-04-10'),
    actualStart: new Date('2026-01-10'),
    actualEnd: null,
    delayDays: 0,
    delayStatus: 'AT_RISK',
    phase: 'MIGRATION',
    status: 'ON_HOLD',
    sourcePlatform: 'Legacy EHR',
    targetPlatform: 'Epic Systems',
    estimatedCost: 200000,
    actualCost: null,
    description: 'Electronic Health Records system migration.',
    notes: 'On hold pending regulatory approval.',
    createdAt: new Date('2026-01-05'),
    updatedAt: new Date('2026-03-20'),
  },
  {
    id: '6',
    name: 'EduTech Learning Platform',
    customerName: 'EduTech Solutions',
    projectManager: 'Mark Johnson',
    accountManager: 'Sarah Johnson',
    planType: 'BRONZE',
    plannedStart: new Date('2026-02-15'),
    plannedEnd: new Date('2026-03-30'),
    actualStart: new Date('2026-02-15'),
    actualEnd: null,
    delayDays: 0,
    delayStatus: 'NOT_DELAYED',
    phase: 'CLOSURE',
    status: 'ACTIVE',
    sourcePlatform: 'Moodle',
    targetPlatform: 'Canvas LMS',
    estimatedCost: 25000,
    actualCost: null,
    description: 'Learning management system migration.',
    notes: null,
    createdAt: new Date('2026-02-10'),
    updatedAt: new Date('2026-03-25'),
  },
];

export const mockDashboardStats = {
  totalProjects: 6,
  activeProjects: 4,
  completedProjects: 1,
  onHoldProjects: 1,
  delayedProjects: 2,
  atRiskProjects: 1,
  pendingCaseStudies: 1,
  avgDelayDays: 10,
};

export const mockProjectsByStatus = [
  { status: 'ACTIVE', count: 4 },
  { status: 'COMPLETED', count: 1 },
  { status: 'ON_HOLD', count: 1 },
];

export const mockProjectsByPhase = [
  { phase: 'KICKOFF', count: 1 },
  { phase: 'MIGRATION', count: 2 },
  { phase: 'VALIDATION', count: 1 },
  { phase: 'CLOSURE', count: 1 },
];

export const mockProjectsByPlan = [
  { planType: 'PLATINUM', count: 2 },
  { planType: 'GOLD', count: 2 },
  { planType: 'SILVER', count: 1 },
  { planType: 'BRONZE', count: 1 },
];

export const mockRecentActivity = [
  {
    id: '1',
    type: 'project_updated',
    projectName: 'TechStart SaaS Migration',
    projectId: '2',
    timestamp: new Date(),
    details: 'Project updated - Phase: VALIDATION, Status: ACTIVE',
  },
  {
    id: '2',
    type: 'delay_detected',
    projectName: 'TechStart SaaS Migration',
    projectId: '2',
    timestamp: new Date(Date.now() - 86400000),
    details: 'Delay detected: 6 days behind schedule',
  },
  {
    id: '3',
    type: 'project_created',
    projectName: 'RetailMax E-commerce Platform',
    projectId: '4',
    timestamp: new Date(Date.now() - 172800000),
    details: 'New project created',
  },
];

export const mockDelaySummary = {
  byStatus: [
    { status: 'NOT_DELAYED', count: 3 },
    { status: 'AT_RISK', count: 1 },
    { status: 'DELAYED', count: 2 },
  ],
  topDelayed: [
    { id: '3', name: 'GlobalBank Data Center Move', delayDays: 15, customerName: 'Global Bank Ltd' },
    { id: '2', name: 'TechStart SaaS Migration', delayDays: 6, customerName: 'TechStart Inc' },
  ],
};

export const mockUpcomingDeadlines = [
  {
    id: '6',
    name: 'EduTech Learning Platform',
    customerName: 'EduTech Solutions',
    plannedEnd: new Date('2026-03-30'),
    daysRemaining: 4,
    phase: 'CLOSURE',
  },
  {
    id: '5',
    name: 'HealthCare Plus EHR Migration',
    customerName: 'HealthCare Plus',
    plannedEnd: new Date('2026-04-10'),
    daysRemaining: 15,
    phase: 'MIGRATION',
  },
];
